FROM ubuntu
RUN apt-get update
RUN apt-get install -y python
ADD sample.py /home/sample.py
ENTRYPOINT ["python", "/home/sample.py"]



# FROM python:3.9
# WORKDIR /usr/app
# VOLUME data
# USER root
# RUN pwd
# COPY sample.py ./
# RUN pwd
# ENTRYPOINT [ "python", "sample.py" ]